[package]
name = "piston-tetris"
version = "0.1.0"
authors = ["Edgar Nova <ragnarok540@gmail.com>"]
edition = "2021"

[dependencies]
piston = "0.53.2"
piston2d-graphics = "0.43.0"
piston2d-opengl_graphics = "0.82.0"
pistoncore-glutin_window = "0.71.0"
rand = "0.8.5"
